project:
  type: website
website: 
  title: "Blog Posts"
  navbar:
    right:
     # - text: "Consulting/Freelance"
     #   href: consulting.html
      - text: "About Me"
        href: about.qmd
     #  - text: "Consulting"
     #  href: freelance.qmd
      # - text: "Newsletter"
      #   href: newsletter.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/rwe-ryan
      - icon: twitter
        href: https://twitter.com/rwe_ryan
      - icon: github
        href: https://github.com/battenr

format:
  html:
    theme: flatly
    # css: styles.css

editor: visual

