project:
  type: website

website:
  title-block-categories: false
  # sidebar: 
  #   style: "docked"
  #   search: true
  #   contents:
  #     - section: "Welcome"
  #       contents: 
  #         - posts/welcome/welcome.qmd
  #     - section: "Real World Evidence"
  #       contents:
  #         - posts/rwe-whats-the-hype/rwe_intro.qmd
  #     - section: "Causal Inference" 
  #       contents:
  #         - posts/causal_inference_intro/causal_inference.qmd
  #     - section: "P-Values and Power"
  #       contents: 
  #         - posts/p-value-power/p-value-power.qmd
  #     - section: "Effect Estimates"
  #       contents: 
  #         - posts/or_rr_hr/or_rr_hr.qmd
  title: "Ryan's Real-World Experience"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/battenr
      - icon: twitter
        href: https://twitter.com/rwe_ryan
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

