project:
  type: website
website: 
  title: "Ryan's Real-World Evidence"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/battenr
      - icon: twitter
        href: https://twitter.com/rwe_ryan
format:
  html:
    theme: flatly
    # css: styles.css

editor: visual

