{
  "hash": "2b050ac1c3e8ada646ce459ef88c3c17",
  "result": {
    "markdown": "---\ntitle: \"Causal Estimands\" \nsubtitle: \"Who does this apply too?\"\nauthor: \"Ryan Batten\"\ndate: \"2023-06-22\"\ncategories: [Estimands, ATE, ATT, ATU, ATO]\n# image : \"standards.png\"\nbibliography: estimands.bib\ndraft: true\nformat: \n  html:\n    toc: true\n    toc-title: Contents\n    toc-location: right\n    toc-depth: 4\n    code-fold: true\n---\n\n\n## Who does this apply too?\n\nA key part of any research question is to figure out who our *target population* is. These are the people we want to study. For example, is it 85 year olds who play american football? Is it children between 5-11 years of age using the swings at the park? Figuring this out, allows us to figure out who to sample but also who our results will apply too. The best way to explain this is through an example, so without further ado let's get started!\n\n## Magical Water Gun for Height?\n\nSay that we have a magical water gun that makes you grow taller. Before we do any analyses, we need to setup our research question. In clinical epidemiology this is typically PICO(S): **p**opulation, **i**ntervention, **c**omparators, **o**utcome and sometimes **s**tudy design (I say sometimes because it's not always clearly defined, but can be figured out based on looking at the type of study).\n\nThe causal estimand helps us with the first letter: P by asking \"who does this apply too?\". Now the who refers to the *target* population, that is the people we are...well targeting.\n\n![Monsters](kids_monsters.png){#fig-sample}\n\nImagine that there is a magical water gun that monsters from space (aka aliens) have shown up to earth with. They've sprayed some of themselves with it, and some kids who want to grow taller. We want to know if this will actually work! Why? Well both monsters and kids are pretty short, their friends want to know if they will grow! (cue the monstars from Space Jam). @fig-sample shows what our sample looks like. As you can see, there's a mixture of monsters and kids in each group.\\\n\\\nThe figure is illustrative. Let's look at the actual characteristics from the individuals we will be studying outlined in @tbl-characteristics.\n\n\n::: {.cell}\n\n:::\n\n\n+-----------------------------+----------------------+----------------+\n|                             | Sprayed by Water Gun | Not Sprayed    |\n|                             |                      |                |\n|                             | (n = 458)            | (n = 129)      |\n+:===========================:+:====================:+:==============:+\n| Number of eyes, mean (SD)   | 2.59 (1.31)          | 2.38 (1.29)    |\n+-----------------------------+----------------------+----------------+\n| Age, mean (SD)              | 27.75 (40.4)         | 23.27 (37.83)  |\n+-----------------------------+----------------------+----------------+\n| Monsters, n (%)             | 110 (24.0%)          | 25 (19.4%)     |\n+-----------------------------+----------------------+----------------+\n| Height (in feet), mean (SD) | 1.71 (0.65)          | 1.60 (0.66)    |\n+-----------------------------+----------------------+----------------+\n\n: Characteristics {#tbl-characteristics}\n\nThere were 458 individuals sprayed by the water gun, while 129 were not sprayed. There's differences in age (as we'd expect with monsters!) and percentage of monsters. Looking at just height, you could think that this magical water gun works! However....and a big however...does it? Or is it just that it works better on monsters? Or that monsters are taller?\\\n\\\nNow, confounding aside, what do we want to know? Who to spray with this gun! It's not quite as simple and straightforward as that. Let's briefly go over the four estimands we'll be talking about in this case.\n\n## Types of Estimands\n\nWe'll focus on four causal estimands, in no particular order:\n\n-   Average treatment effect in the population (ATE)\n\n-   Average treatment effect in the treated (ATT)\n\n-   Average treatment effect in the untreated (ATU)\n\n-   Average treatment effect in the overlap (ATO)\n\nOne important thing to note here is that all of these estimands would be the same in a randomized trial because the characteristics will be the same (at least in theory). Therefore the ATT, ATU and ATE will be the same. However, not so in observational data.\n\n## Potential Outcomes\n\n::: callout-note\nAn important part here is the potential outcomes framework. The potential outcomes can be written as $Y_0$ and $Y_i$. For a binary treatment, like in our case, we can think of it as each person has two potential outcomes (one if they get sprayed by the water gun, one if not). Depending on what happens, one of the outcomes is observed.\\\n\\\nNow, the individual causal effect is $Y_1$ - $Y_0$ for each person. We can't know this for each person, so instead we take an average (if we assume certain things). In math terms, we show this as $E[Y_{1} - Y_{0}]$.\n:::\n\n::: callout-note\n## Propensity Score\n\nWe will be using propensity scores to estimate each of these estimands. A brief overview of the propensity is that it's the conditional probability of treatment conditional on covariate. More simply put: it's the probability of being a monster based on the number of yours eyes.\n:::\n\n### ATE\n\nAsk yourself: would it be feasible to treat all eligible people included in the study (in this case all the monsters and kids) with the treatment of interest? If yes, then we could look at the ATE [@desai2019].\n\nThe ATE is the the average treatment effect among all eligible patients in the study population (i.e., difference were they all to be treated vs were they all not to be treated) [@greifer2021choosing]. For our example, it would be the difference were all the monsters and kids sprayed with the water gun versus were all the monsters and kids not sprayed. In mathematical notation it's:\n\n$$E[Y_{1}-Y_{0}]$$\n\nTo estimate the ATE, we can use inverse probability weights. To calculate these, we need the propensity score (PS). Once we have it, the equation is $1/{PS}$ for the treated group and $1/(1-{PS})$ for the control group. Then we can plug these weights into the outcome model and away we go!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# First, fit a model for the treatment (in this case our water gun)\n\nps.mod <- glm(sprayed ~ eyes + group, \n              family = binomial(link = \"logit\"), \n              data = df)\n\n# Use \n\ndf.ps <- df %>% \n  dplyr::mutate(\n    ps = predict(ps.mod, type = \"response\"), \n    weights_ate = dplyr::case_when(\n      \n      # Note: for simplicity using unstabilized weights \n      \n      sprayed == 1 ~ 1/ps, \n      sprayed == 0 ~ 1/(1-ps)\n    )\n  )\n\noutcome.mod <- glm(height ~ as.character(sprayed),\n                   family = gaussian(link = \"identity\"),\n                   weights = weights_ate, \n                   data = df.ps)\n\nsandwich_se <- diag(sandwich::vcovHC(outcome.mod, type = \"HC\"))^0.5\n\noutcome <- broom::tidy(outcome.mod) |> \n  dplyr::filter(\n    term == \"as.character(sprayed)1\"\n  ) |> \n  dplyr::mutate(\n   upper.ci = estimate + qnorm(0.975)*sandwich_se[2],\n   lower.ci = estimate - qnorm(0.975)*sandwich_se[2], \n  )\n\npaste0(round(outcome$estimate, 3), \" 95% CI (\", round(outcome$lower.ci,3), \" to \", round(outcome$upper.ci, 3), \")\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"0.022 95% CI (-0.109 to 0.154)\"\n```\n:::\n:::\n\n\nTa da! Now we know that being sprayed with a water gun doesn't affect the height in our ATE population (that is if everyone was sprayed compared to if everyone was not sprayed). But what about if not everyone is eligible for the treatment?\n\n### ATT\n\nNow we ask, would the treatment only be given to patients with certain characteristics? If yes, then the ATT might be of interest [@desai2019]. For example, what if only individuals over the age of 5 could be treated? Would it work in them? In mathematical notation:\n\n$$E[Y_{1}-Y_{0}|T = 1]$$\n\nIn term of weights, all of the patients in the treated group get a value of $1$ while those in the control get a value of $PS / (1-PS)$. This is known as standardized mortality ratio weights.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.ps <- df %>% \n  dplyr::mutate(\n    ps = predict(ps.mod, type = \"response\"), \n    weights_att = dplyr::case_when(\n      \n      # Note: for simplicity using unstabilized weights \n      \n      sprayed == 1 ~ 1, \n      sprayed == 0 ~ ps/(1-ps)\n    )\n  )\n\noutcome.mod <- glm(height ~ as.character(sprayed),\n                   family = gaussian(link = \"identity\"),\n                   weights = weights_att, \n                   data = df.ps)\n\nsandwich_se <- diag(sandwich::vcovHC(outcome.mod, type = \"HC\"))^0.5\n\noutcome <- broom::tidy(outcome.mod) |> \n  dplyr::filter(\n    term == \"as.character(sprayed)1\"\n  ) |> \n  dplyr::mutate(\n   upper.ci = estimate + qnorm(0.975)*sandwich_se[2],\n   lower.ci = estimate - qnorm(0.975)*sandwich_se[2], \n  )\n\npaste0(round(outcome$estimate, 3), \" 95% CI (\", round(outcome$lower.ci,3), \" to \", round(outcome$upper.ci, 3), \")\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"0.022 95% CI (-0.11 to 0.154)\"\n```\n:::\n:::\n\n\nOur results are similar but not the same as those for the ATE!\n\n### ATU\n\nThe ATU is similar to the ATT except opposite (okay admittedly that sentence isn't fully coherent). For our study the question would be \"Are there people who would not be treated? For example, what about in those individuals under 5?\". In mathematical notation:\n\n$$E[Y_{1}-Y_{0}|T = 0]$$\n\nIn terms of weights it's the opposite of the ATT: $1$ for those in the control group and $(1-PS)/PS$ for the treated group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.ps <- df |> \n  dplyr::mutate(\n    ps = predict(ps.mod, type = \"response\"), \n    weights_atu = dplyr::case_when(\n      \n      # Note: for simplicity using unstabilized weights \n      \n      sprayed == 1 ~ (1-ps)/ps, \n      sprayed == 0 ~ 1\n    )\n  )\n\noutcome.mod <- glm(height ~ as.character(sprayed),\n                   family = gaussian(link = \"identity\"),\n                   weights = weights_atu, \n                   data = df.ps)\n\nsandwich_se <- diag(sandwich::vcovHC(outcome.mod, type = \"HC\"))^0.5\n\noutcome <- broom::tidy(outcome.mod) |> \n  dplyr::filter(\n    term == \"as.character(sprayed)1\"\n  ) |> \n  dplyr::mutate(\n   upper.ci = estimate + qnorm(0.975)*sandwich_se[2],\n   lower.ci = estimate - qnorm(0.975)*sandwich_se[2], \n  )\n\npaste0(round(outcome$estimate, 3), \" 95% CI (\", round(outcome$lower.ci,3), \" to \", round(outcome$upper.ci, 3), \")\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"0.023 95% CI (-0.104 to 0.15)\"\n```\n:::\n:::\n\n\n### ATO\n\nATO is the average effect of the treatment in the overlap. Those patients who it's unclear if the benefits would outweigh the costs [@greifer2021choosing]. These patients are very similar to each other but less similar for patients who the treatment decisions are more \"clear cut\" so to say [@greifer2021choosing]. In mathematical notation:\n\n$$E[Y_{1}-Y_{0}]$$\n\nNow something you might notice here is that the equation is the same as above for the ATE. Why is that? Well it's because we are still reweighing both the treated and control groups but it's a different target population. Instead of it being \"everyone\" like above, it's the people who are in the uncertain group. We weight them as $PS$ for the sprayed group and $1-PS$ for the not sprayed group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.ps <- df |> \n  dplyr::mutate(\n    ps = predict(ps.mod, type = \"response\"), \n    weights_ato = dplyr::case_when(\n      \n      # Note: for simplicity using unstabilized weights \n      \n      sprayed == 1 ~ (1-ps), \n      sprayed == 0 ~ ps\n    )\n  )\n\noutcome.mod <- glm(height ~ as.character(sprayed),\n                   family = gaussian(link = \"identity\"),\n                   weights = weights_ato, \n                   data = df.ps)\n\nsandwich_se <- diag(sandwich::vcovHC(outcome.mod, type = \"HC\"))^0.5\n\noutcome <- broom::tidy(outcome.mod) |> \n  dplyr::filter(\n    term == \"as.character(sprayed)1\"\n  ) |> \n  dplyr::mutate(\n   upper.ci = estimate + qnorm(0.975)*sandwich_se[2],\n   lower.ci = estimate - qnorm(0.975)*sandwich_se[2], \n  )\n\npaste0(round(outcome$estimate, 3), \" 95% CI (\", round(outcome$lower.ci,3), \" to \", round(outcome$upper.ci, 3), \")\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"0.022 95% CI (-0.106 to 0.151)\"\n```\n:::\n:::\n\n\n## Choose Your Adjustment Technique Wisely!\n\nPicking the estimand of interest isn't just important for the target population but also for the adjustment technique selected. Certain ones can only target certain estimands. This becomes even more important when you are comparing methods. For example, IPW and PSM do not target the same estimand [@greifer2021choosing]. There is a great flowchart for the steps involved by @desai2019, I highly recommend it if you are trying to determine the appropriate adjustment techinque.\n\n## Next Steps\n\nWhat's next? Well know you can go out into the world and answer all your burning questions like \"Does this magical water gun actually work?\" and followup with \"Who exactly does it work on?\"\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}