---
title: "Table 2 Fallacy Takeaways" 
subtitle: "TBD"
author: "Ryan Batten"
date: "2023-03-02"
categories: [Nested Models, G-Estimation]
# image : "standards.png"
bibliography: table2_fallacy.bib
draft: true
format: 
  html:
    toc: true
    toc-title: Contents
    toc-location: right
    toc-depth: 4
    code-fold: true
---

## The Table 2 Fallacy

One of my favorite articles (to date anyways), is the Table 2 Fallacy [@westreich2013table]. To summarize briefly, even though this does it an injustice, the main takeaway is that you should not report the effect estimates of

## What does this mean? 

Well it mean's a few things. One of the key takeaways for me, was in fitting a model when we are predominantly interest in the exposure-outcome relationship. For continuous outcomes, often times fitting it as a simple linear predictor is used due to explainability. This can be especially tricky when the continuous predictor and outcome do not have a linear relationship.

A good example of this is age. Age is often not continuous, so we can try to fit a model with additional terms or polynomials (i.e., age squared) but this can make it tricky to interpret. Not only are we wrong to report this but it makes it difficult to interpret.

::: callout-tip
## Interpretability

You may be thinking to yourself "Why should we care about interpretability?". Well, from a practical perspective if you give me two models, one that is a better fit and more appropriate but nearly impossible to interpret or one that isn't as good of a fit, but easier to interpret, I'm picking that one. \
\
"Why?!" you may be screaming at your screen right now. Well the answer is simply from a practical perspective: if your model can't be interpreted, it won't be used. Chances are, if it was tricky for you to figure out how to interpret, the likelihood someone else will be able to understand it is far lower.
:::
