<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ryan Batten">
<meta name="dcterms.date" content="2022-08-02">

<title>Ryan's Real-World Experience – p-values</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Ryan’s Real-World Experience</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">About Me</a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/battenr"><i class="bi bi-github" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/rwe_ryan"><i class="bi bi-twitter" role="img">
</i> 
 </a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">



<section id="overview" class="level1">
<h1>Overview</h1>
<p>P-values are a term commonly heard in scientific literature, however often they are misconstrued, misunderstood or misinterpreted. The p in p-value stands for probability, as a lot of statistics begins with. What exactly does it tell us? Let’s find out</p>
<section id="formal-definitions" class="level2">
<h2 class="anchored" data-anchor-id="formal-definitions">Formal Definitions</h2>
<section id="hypotheses" class="level3">
<h3 class="anchored" data-anchor-id="hypotheses">Hypotheses</h3>
<p>Hypotheses are the best place to start for any science experiment or project. A hypothesis is what you are wanting to know. First you need to start with your research question. For example, are people who love lollipops older than people who do not? To do this, formally in statistics, we need a <em>null hypothesis</em> (<span class="math inline">\(H_0\)</span>) and an <em>alternative hypothesis</em> (<span class="math inline">\(H_A\)</span>). We will use two abbreviations here: LL for lollipop lickers and NLL for not lollipop lickers. We want to know “Do lollipop lickers have more sore tongues than those who do not lick lollipops?”</p>
<p>Re-phrasing this in statistically terms, <span class="math inline">\(H_0\)</span> is that people do not have more sore tongues if they lick lollipops compared to if they do. The question now is what is our alternative hypothesis? Well there are three options to choose from:</p>
<ol type="1">
<li><p>We think LL have more sore tongues than NLL</p></li>
<li><p>We think LL have less sore tongues than NLL</p></li>
<li><p>We don’t know, but we don’t think they are the same!</p></li>
</ol>
<p>1 and 2 are what are called <em>one-sided</em> hypothesis. A one-sided hypothesis, means you are assuming the difference is bigger or smaller. A two-sided hypothesis means we simply don’t know! We will assume we don’t know and use <span class="math inline">\(p\)</span> to denote the proportion of lollipop sore tongues.</p>
<p><span class="math display">\[
H_0: p_{LL-ST} = p_{NLL-ST}
\]</span></p>
<p><span class="math display">\[
H_A: p_{LL-ST} \neq p_{NLL-ST}
\]</span></p>
<p>Now, before we continue we need to review how okay we are with being wrong. Being wrong is okay, but there are two different types of being wrong.</p>
</section>
<section id="type-i-and-ii-errors" class="level3">
<h3 class="anchored" data-anchor-id="type-i-and-ii-errors">Type I and II Errors</h3>
<p>A type I error, sometimes referred to as <span class="math inline">\(\alpha\)</span> error, is the error of saying something happened when it did not. For example, the error of me assuming you bought a balloon <strong>when you did not</strong>. A type II error, sometimes referred to as <span class="math inline">\(\beta\)</span> error, is the error of saying something did not happen <strong>when it did</strong>. Using our balloon example, me assuming you didn’t buy a balloon <strong>when you did</strong>.</p>
</section>
<section id="power" class="level3">
<h3 class="anchored" data-anchor-id="power">Power</h3>
<p>The power of a statistical test is the probability that it correctly rejects the null hypothesis <span class="citation" data-cites="gelman2014beyond">(<a href="#ref-gelman2014beyond" role="doc-biblioref">Gelman and Carlin 2014</a>)</span>. It is tied to the type II error, through the below formula.</p>
<p><span class="math display">\[
Power = 1 - \beta
\]</span></p>
<p>Remember our lollipop example? For that it would be the probability that we can say lollipop lickers do not have the same amount of sore tongues as non lollipop lickers.</p>
</section>
<section id="test-statistic" class="level3">
<h3 class="anchored" data-anchor-id="test-statistic">Test Statistic</h3>
<p>Alright, I know at this point I’m boring you. One last definition and then we can get to the good stuff. A test statistic is exactly what it sounds like. A statistic used for tests! What kind of tests you may ask? Hypothesis tests like we have above. Now, the test statistic in itself may follow a variety of distributions depending on the test. I’ll leave distributions to another post.</p>
</section>
<section id="p-value" class="level3">
<h3 class="anchored" data-anchor-id="p-value">P-Value</h3>
<p>The probability of such an extreme value of the test statistic occurring if the null hypothesis were true is often called the <strong>P-Value <span class="citation" data-cites="bland2015introduction">Bland (<a href="#ref-bland2015introduction" role="doc-biblioref">2015</a>)</span>.</strong></p>
</section>
<section id="significance-level" class="level3">
<h3 class="anchored" data-anchor-id="significance-level">Significance Level</h3>
<p>Remember <span class="math inline">\(\alpha\)</span> from before? The type I error is sometimes referred to as the significance level. The number that is picked for the type I error is usually 0.05, however it is completely arbitrary to pick 0.05. It could be 0.20 or 0.02.</p>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>There is no such thing as <strong><em>more</em></strong> significant. It is either significant at the level that was pre-specified before the analysis or not. For example: a p-value of 0.01 is not <strong>more</strong> significant than a p-value of 0.05</p>
</div>
</div>
</section>
</section>
<section id="sec-problem" class="level2">
<h2 class="anchored" data-anchor-id="sec-problem">Back to our Problem</h2>
<p>Finally, after all those boring definitions we are back to where we started. How are we going to determine whether people who are lollipop lickers have more sore tongues? This requires us to do a bit more thinking to determine the right statistical tool for the toolbox.</p>
<p>Let’s think about this question a bit more first. Lollipop lickers tend to be younger right? Do boys like lollipops more than girls? Let’s assume that both of those things are true. We will want to <em>control</em> for both of those variables. Control in this sense, means adding the variable in the equation like below.</p>
<p><span class="math display">\[
ST = LL + age + sex
\]</span></p>
<p>Now, the type of regression we will use is a <em>generalized linear model (GLM)</em>. Generalized here just means that you can apply to almost any situation, hence general. Another post will cover the differences between GLMs and regular old regression (<em>OLS</em>).</p>
</section>
<section id="data-on-lollipop-lickers-and-sore-tongues" class="level2">
<h2 class="anchored" data-anchor-id="data-on-lollipop-lickers-and-sore-tongues">Data on Lollipop Lickers and Sore Tongues</h2>
<p>Now we know our question, have our tool and want to find out the answer. What are we missing…..the most important thing of all! Data! Luckily, there is a database that collects such data. It has data on 422 people. Below are the summary statistics for our groups</p>
<table class="table">
<colgroup>
<col style="width: 40%">
<col style="width: 29%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;"><p>Sore Tongues</p>
(n = 181)</th>
<th style="text-align: center;"><p>Not Sore Tongues</p>
(n = 241)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Lollipop Lickers, n (%)</strong></td>
<td style="text-align: center;">146 (80.7%)</td>
<td style="text-align: center;">60 (24.9%)</td>
</tr>
<tr class="even">
<td><strong>Age, mean (SD)</strong></td>
<td style="text-align: center;">17.9 (7.30)</td>
<td style="text-align: center;">48.0 (17.8)</td>
</tr>
<tr class="odd">
<td><strong>Female, n (%)</strong></td>
<td style="text-align: center;">107 (59.1%)</td>
<td style="text-align: center;">52 (21.6%)</td>
</tr>
</tbody>
</table>
</section>
<section id="analysis-time" class="level2">
<h2 class="anchored" data-anchor-id="analysis-time">Analysis Time!</h2>
<p>Using our handy dandy formula from above, and our tool from our toolbox (GLM). Below are the results.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)    6.31     1.20        5.25 1.53e- 7
2 ll             2.77     0.484       5.73 1.00e- 8
3 age           -0.317    0.0499     -6.36 2.04e-10
4 sex            2.15     0.493       4.36 1.32e- 5</code></pre>
</div>
</div>
</section>
<section id="now-for-the-interpretation-of-the-p-value" class="level2">
<h2 class="anchored" data-anchor-id="now-for-the-interpretation-of-the-p-value">Now for the Interpretation of the P-Value</h2>
<p>The test statistic for regression is defined by <span class="math inline">\(\beta / SE(\beta)\)</span>. Beta here is the coefficient. For example, the test statistic for age is</p>
<p><span class="math display">\[
-0.3393494/0.0543545 = -6.243
\]</span></p>
<p>Now, this number on it’s own is pretty useless. We want to know, what is our p-value?! Well, to do that we turn to the normal distribution.</p>
</section>
<section id="normal-distribution" class="level2">
<h2 class="anchored" data-anchor-id="normal-distribution">Normal Distribution</h2>
<p>Using the normal distribution, since our sample size is bigger than 30 (a wonderfully random number, that I have no idea why it’s 30), we can determine our almighty p-value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">6.243</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.292569e-10</code></pre>
</div>
</div>
<p>Ta-da! We have our p-value of 4.29e-10. This is less than our pre-specified value of 0.05. We can therefore use significant in our interpretation however there are some strong caveats we need to go over first.</p>
</section>
<section id="issues-with-the-p-value" class="level2">
<h2 class="anchored" data-anchor-id="issues-with-the-p-value">Issues with the P-Value</h2>
<p>P-values are typically over emphasized. They are a piece of the puzzle, however they are not the whole puzzle. Arguably, a more important piece of the puzzle is the effect size. For our example, lollipop lickers have increased odds of a sore tongue compared to non-lollipop lickers (OR = 5.87, 95% CI: 2.53 to 13.87). The effect, in this case OR, should be another piece of the puzzle that is considered. Finally, there are two other errors we should go over that highlight how not confident we can be in the p-value.</p>
<section id="type-m-type-s-error" class="level3">
<h3 class="anchored" data-anchor-id="type-m-type-s-error">Type M &amp; Type S Error</h3>
<p>Often type I and type II errors are highlighted however type M and type S errors are important to note as well. A type S error is the probability of an estimate being in the wrong direction <span class="citation" data-cites="gelman2014beyond">(<a href="#ref-gelman2014beyond" role="doc-biblioref">Gelman and Carlin 2014</a>)</span>. A type M error is the factor by which the magnitude of an effect might be overestimated <span class="citation" data-cites="gelman2014beyond">(<a href="#ref-gelman2014beyond" role="doc-biblioref">Gelman and Carlin 2014</a>)</span>. Definitions are always great but an example helps to better understand.</p>
<p>Using our example from before, and the function outlined in <span class="citation" data-cites="gelman2014beyond">Gelman and Carlin (<a href="#ref-gelman2014beyond" role="doc-biblioref">2014</a>)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>retrodesign <span class="ot">&lt;-</span> <span class="cf">function</span>(A, s, <span class="at">alpha=</span>.<span class="dv">05</span>, <span class="at">df=</span><span class="cn">Inf</span>, <span class="at">n.sims=</span><span class="dv">10000</span>){</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  z <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>, df)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  p.hi <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(z<span class="sc">-</span>A<span class="sc">/</span>s, df)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  p.lo <span class="ot">&lt;-</span> <span class="fu">pt</span>(<span class="sc">-</span>z<span class="sc">-</span>A<span class="sc">/</span>s, df)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  power <span class="ot">&lt;-</span> p.hi <span class="sc">+</span> p.lo</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  typeS <span class="ot">&lt;-</span> p.lo<span class="sc">/</span>power</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  estimate <span class="ot">&lt;-</span> A <span class="sc">+</span> s<span class="sc">*</span><span class="fu">rt</span>(n.sims,df)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  significant <span class="ot">&lt;-</span> <span class="fu">abs</span>(estimate) <span class="sc">&gt;</span> s<span class="sc">*</span>z</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  exaggeration <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(estimate)[significant])<span class="sc">/</span>A</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">list</span>(<span class="at">power=</span>power, <span class="at">typeS=</span>typeS, <span class="at">exaggeration=</span>exaggeration))</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="fu">retrodesign</span>(<span class="sc">-</span><span class="fl">0.0339</span>, <span class="fl">0.0543545</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$power
[1] 0.09561688

$typeS
[1] 0.9488784

$exaggeration
[1] -3.898453</code></pre>
</div>
</div>
<p>The type S error is 0.948, while the type M error is -3.81our type S error would be 0.949 and type M error of 3.87. This means that there is a 94.9% probability that the estimate is the wrong sign, and that the value is overestimated by 3.87 times. Doesn’t sound good right?</p>
</section>
</section>
<section id="so-are-p-values-garbage" class="level2">
<h2 class="anchored" data-anchor-id="so-are-p-values-garbage">So are p-values garbage?</h2>
<p>P-values have a place in science, however they should be interpreted with caution and as a piece to the puzzle. Other pieces include the effect size, study design, sample that was studied and a myriad of other components.</p>



</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-bland2015introduction" class="csl-entry" role="doc-biblioentry">
Bland, Martin. 2015. <em>An Introduction to Medical Statistics</em>. Oxford university press.
</div>
<div id="ref-gelman2014beyond" class="csl-entry" role="doc-biblioentry">
Gelman, Andrew, and John Carlin. 2014. <span>“Beyond Power Calculations: Assessing Type s (Sign) and Type m (Magnitude) Errors.”</span> <em>Perspectives on Psychological Science</em> 9 (6): 641–51.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>