---
title: "Hot Diggity DAG" 
subtitle: "An introduction to DAGs"
author: "Ryan Batten"
date: "2023-07-15"
categories: [DAGs, Causal Diagrams]
# image : "standards.png"
bibliography: dags.bib
draft: true
format: 
  html:
    toc: true
    toc-title: Contents
    toc-location: right
    toc-depth: 4
    code-fold: true
---

## "Don't Analyze Graphs?"

Yes..well no...well kinda. DAG in this case, stands for Directed Acyclic Graph. Simply put, it is a graph that is directed and acyclic...alright that's not much of an explanation. Let's try again: a causal DAG shows how your variables are related. To quote Miguel Hernan, since I couldn't have said it better myself, "Draw your assumptions before your conclusions".

## Why should I?

A perfectly valid question at this point is "Why should I? I don't need these". The phrase a picture is worth a thousand words applies here too.

## Does Coffee Increase My Alertness?

I'm an avid coffee drinker. I love hot coffee, iced coffee, cold brew, nitro cold brew...you name it, I'm in (unless it's bad coffee). Something I often wonder is if drinking a lot of coffee actually improves my alertness or not. That is, does coffee cause my alertness? Let's start here. We'll assume that coffee does cause alertness and draw a line between the two.

```{r, message=FALSE}

library(tidyverse)
library(ggdag)
theme_set(theme_dag())

coffee_dag <- ggdag::dagify(
  alert ~ coffee, 
  exposure = "coffee",
  outcome = "alert",
  labels = c(
    coffee = "Coffee",
    alert = "Alertness"
  )
)

ggdag::ggdag(coffee_dag, text = FALSE, use_labels = "label")

```

This looks great but there's one glaring problem....there are many, many, MANY variables that affect both of these variables. How much you've slept, stress and hunger just to name a few. Not to mention that each of those variables are related.\
\
So our DAG needs some editing, but first we need to go over some assumptions or "house rules" per say.

## Assumptions of DAGs

Let's start with the acronym. They are called DAGs because they have a direction and cannot have a variable that causes itself, either directly or through another variable [@hernanwhatif, pp. 72].

Another key component is the causal Markov assumption, which put simply is that a variable is independent of any variable that it isn't a cause for (for more details about this check out @hernanwhatif, pp. 72). This assumption means that in a causal DAG, the common causes of any pair of variables in the graph must also be in the graph.\
\
For example,

### D-Separation

The rules are like so [@hernanwhatif, pp. 78]:

1.  If no variables are being conditioned on, a path is blocked if and only if two arrowheads on the path collide at some variable on the path.

2.  Any path that contains a non-collider that has been conditioned on is blocked.

3.  A collider that has been conditioned on does not block a path.

4.  A collider that has a descendant that has been conditioned on does not block a path.

::: callout-note
## Causal Graph Theory

There is some complex math behind these rules that I won't go into here. If you are interested, I recommend checking out the work of Judea Pearl, or some sections of @hernanwhatif.
:::

We will summarize d-separation like so: a path is blocked if and only if, it contains a non-collider that has been conditioned on, or it contains a collider that has not been conditioned on and has no descendants that have been conditioned on [@hernanwhatif, pp. 78].

Two variables are d-separated if all paths between them are blocked (otherwise we say they're d-connected) [@hernanwhatif, pp. 78].

## Uses of DAGs

Great, so we now know how to draw a DAG but is this even useful? Absolutely! It can be used for variable selection, etc, etc.

## Why do we need a DAG?

Before we get started into what it actually is and the rules, it's always a good idea to review the why.

You should

(can ref/talk about riley2022 12 days of christmas statisitician article)

## Simple DAG

## "Think of Water Flowing in a Pipe"....What?

One of the peskiest biases

## Title ideas (from ChatGPT)

Sure, how about "Don't Analyze Graphs"? It's a bit tongue-in-cheek, implying that you should just trust the Directed Acyclic Graph (DAG) without over-analyzing it. Of course, in reality, careful analysis is often necessary to ensure the accuracy and validity of DAGs used in various applications such as machine learning.

How about "Dramatic Action Graph"? It's not necessarily hilarious, but it adds a bit of flair to the otherwise technical-sounding term DAG!
