---
title: "Missing Data" # November Post 
subtitle: "The Where's Waldo of Causal Inference" # Titles are placeholders
author: "Ryan Batten"
date: "2023-11-15"
categories: [Missing Data]
# bibliography: bootstrap.bib
draft: true
format: 
  html:
    code-fold: true
---

# Missing Data

Missing data are inevitable when dealing with real-world data. Due to this, it's important to have a plan for dealing with missing data. There are tons of different methods that can be used for missing data but this post will focus on four methods: multiple imputation, k nearest neighbour imputation, regression imputation and last observation carried forward. In order to make a valid causal inference we need to have an appropriate plan.

Before we get started, we need to go over the different types of missing data mechanisms. Basically, what are the ways that data comes to be missing.

# Missing Data Mechanisms

\[NOTE TO SELF: AUSTIN 2021 has some good definitions for MCAR, MAR and MNAR)

There are three types of missing data mechanism: missing completely at random (MCAR), missing at random (MAR) and missing not at random (MNAR). Each of these has different assumptions and needs to be handled accordingly. But what exactly are they? Without further ado, let's jump in!

## Missing Completely at Random (MCAR)

Missing completely at random is the just that. The key word is "completely". This means that it has nothing to do with the other variables that we are interested in. Let's use an example

## Missing at Random (MAR)

## Missing Not at Random (MNAR)

# Picking a Method

There are several methods which we'll go over below. The layout is as follows: overview of what the method is, assumptions (what's required of the method), use cases and then an example in R.

# Multiple Imputation

## How Does it Work?

# K Nearest Neighbour Imputation

K nearest neighbour imputation is a mouthful. So let's break it down. Essentially, what happens is you match people to the closest person. Based on this, you assume that their value is the same as this "closest" person. Why K? Well it's doesn't have to just be one person, it could be a couple (RYAN: how does this work)\>

# Regression Imputation

# Last Observation Carried Forward

# Summary of Methods

It's important to remember there isn't
